### ISSUE TITLE
Overall code review

### ISSUE THREAD

**Issue by zhongsp** [CVBDL/RaLibraryServer#13]
Fixed: 2, 4

**Comment by mingmingruyuedlut** [comment]
1):
UserController.cs: 
Customized attribute: RaLibraryAuthorize(Roles = ....) can move to controller level if all actions use the same one. Such as the UserController.cs

2):
UserController.cs:
var logRecord = db.BorrowLogs.Where(log => log.F_BookID == id && log.ReturnTime == null).First();

Also can use this method (more simple and efficient):
var logRecord = db.BorrowLogs.First(x=> x.F_BookID == id && x.ReturnTime == null);

**Comment by mingmingruyuedlut** [comment]
If we have time, we can modify the structure about this solution to make it more clearly and expandable.

3):
 BookController.cs and UserController.cs:

 Can add another layer (such as DBManager) to handle the logic about db.
 Don't operate the db through Entity Framework in Api Controller directly.
 Example:
 ApiController -> DBManager -> Entity Framework(db)

4): 
Models:
The classes in this folder is the models that provided to UI side.
Need move current db models (Book.cs and BorrowLog.cs) to 'Entity' folder.
And add the mapping between 'Entity' and 'Model'

5):
Separate the structure about db EntityFramework from current project:
Can add another project or new folders to current Solution.
And move RaLibraryContext.cs, Configuration.cs and Entity to this new project or the new folders.
(new project is better)

Can according to this link  :)  https://github.com/mingmingruyuedlut/SmartStock/tree/master/SmartStock.Core

**Comment by mingmingruyuedlut** [comment]
Just discussing: 
Is it better to move ToDto calling from Controllers to Managers also?

eg:
         public async Task< BookDto > GetAsync(int id) 
         { 
             Book book = await db.Books.FindAsync(id); 
             if (book == null) 
             { 
                 throw new DbRecordNotFoundException(); 
             } 
             else 
             { 
                 return ToDto(book); 
             } 
         }

**Comment by zhongsp** [comment]
Close for now.
