### ISSUE TITLE
It should notify book borrower 2 weeks before book's return date

### ISSUE THREAD

**Issue by zhongsp** [CVBDL/RaLibraryServer#20]

**Comment by mingmingruyuedlut** [comment]
We can use 'Quartz.Net' to implement the scheduler/timer job.
Referenced Links: 
https://www.codeproject.com/Articles/860893/Scheduling-With-Quartz-Net
https://stackoverflow.com/questions/8821535/simple-working-example-of-quartz-net

Then create the windows service to host the scheduler.
Referenced Links:
http://www.codingdefined.com/2016/08/schedule-tasks-as-windows-service-using.html
http://www.c-sharpcorner.com/UploadFile/8f2b4a/how-to-installuninstall-net-windows-service-C-Sharp/

**Comment by zhongsp** [comment]
Completed.
