### ISSUE TITLE
Authentication JWT generation

### ISSUE THREAD

**Issue by zhongsp** [CVBDL/RaLibraryServer#6]
Sample:

```js
header = {
  "alg": "HS256",
  "typ": "JWT"
}

payload = {
  // A JSON numeric value representing the number of seconds from
  // 1970-01-01T00:00:00Z UTC until the specified UTC date/time,
  // ignoring leap seconds.
  "exp": 1483200000,
  "email": "patrick.zhong@example.com"
}
```

It should be able to read the sign secret from system environment variable `RALIBRARY_JWT_KEY`.

Example:

```
RALIBRARY_JWT_KEY = "ralibrary"
```

Then use `"ralibrary"` to sign the header and payload, generates a JWT.

The expected result JWT would be: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0ODMyMDAwMDAsImVtYWlsIjoicGF0cmljay56aG9uZ0BleGFtcGxlLmNvbSJ9.E41uEnlFDhLk_05ftd95xNdbxSuVpO1X1TTJ5uJDStE`

**Comment by bdong1988** [comment]
Complete implementation of domain authentication module.

**Comment by zhongsp** [comment]
2 days. @LuciferQiLiao
